### ISSUE TITLE
Peer review van Maylinn

### ISSUE THREAD

**Issue by MaylinnK** [sahitj001/frontend-applications#3]
**Code:** 
- [x] -Er staan nog best veel console.logs in de code.
- [x] -Verander de oude chart bestandnamen naar prototype/gravechyard :)  
+Veel duidelijke comments.
+Genoeg witruimte om de code te ordenen.
+Bronvermeldingen.

**Documentatie:**
- [x] -Misschien de link van de deployde versie in de "About" zetten.
+Nette Readme met afbeeldingen/gifs
+Ik heb hier weinig over op te merken.  Het is heel uitgebreid en gedetailleerd, misschien kun je nog een kopje toevoegen over wat je nog had willen toevoegen als je meer tijd had.

**Comment by jor-s** [comment]
Duidelijk! Ik zal aan de punten werken.

**Comment by jor-s** [comment]
De feedback is verwerkt!
