### ISSUE TITLE
Peer review Txai

### ISSUE THREAD

**Issue by Txai-HvA** [sahitj001/frontend-applications#4]
**Gitignore:** Aanwezig
**Link to live demo on github pages:** Staat in de READ.ME. Zou handig zijn als het ook in de About staat van je github pagina.
**Description:** Staat in de READ.ME en het is duidelijk.
**Concept:** Concept staat ook in de READ.ME. Ook handig dat je onderzoeksvragen heb bedacht op basis van de data die jouw grafieken tonen.
**Image:** Staat in de READ.ME. Het is een gifje die je een rondleiding geeft door de app.
**Link to example used to build visualization:** Bronnenlijst per hoofdstuk.
**Data used (what's done with invalid and empty values?):** Die zijn niet aanwezig.
**(Link to) functional pattern:** Niet aanwezig.
**Plagiarism and acknowledgements:** Niet aanwezig.
**Read the wiki, can you follow the datacleaning and transforming process?:** Het is te volgen en het is zeer uitgebreid.
**Code:** 
Ik zou de console.log's, dode/gecommente code en files die je niet gebruikt weghalen. 
Er wordt netjes ingespringt en het is leesbaar. Misschien een variabele maken voor 'Hover over a bar!' bij je useStates. 

**Rubric**
**Application of the subject matter:** Data wordt gelezen en veranderd.
**Quality:** Code kwaliteit is goed en de documentatie is duidelijk en uitgebreid.
**Process:** Process is uitgebreid beschreven.

**Comment by jor-s** [comment]
Thanks voor de feedback! Ik zal de dode components/console.logjes weghalen. Ik zal ook kijken of ik mijn functional pattern kan toevoegen in de wiki.

**Comment by jor-s** [comment]
Alle feedback is verwerkt!
